name: Milestones
version: 1.0
author: Wertik1206
main: me.wertik.milestones.Main
description: Logging data, doing some cool stuff
softdepend: [PlaceholderAPI]
commands:
  milestones:
    aliases: [mile, miles]
    description: Main plugin command