name: Milestones
version: 2.0
author: Wertik1206
main: me.wertik.milestones.Main
description: Loging data, doing some cool stuff.
softdepend: [PlaceholderAPI]
commands:
  milestones:
    aliases: [mile, miles]
    description: Main plugin command, try out.
  datastorage:
    aliases: [ds, datas, dstorage]
    description: Manipulates the database.