name: Milestones
version: 1.1.2
author: Wertik1206
main: me.wertik.milestones.Main
description: Logging data based on conditions
softdepend: [PlaceholderAPI, Vault]
commands:
  milestones:
    aliases: [mile, miles]
    description: Main plugin command